apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: dev
  labels:
    name: nginx-test
    type: testing
spec:
  containers:
  - name: nginx-test
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80