apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rc
  labels:
    app: nginx-rc
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-rc
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
