apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP ##<-- no need to mention, default service is clusterip
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
